name: Build And Deploy Code
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["feature X"]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            -   name: pulling git repo
                uses: actions/checkout@v4
            -   name: Say Hi To Rayen
                run: echo "Hello Rayen !"
