name: Build And Deploy Code
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["feature X"]

jobs:
    job1:
        env:
            DATABASE_HOSTNAME: localhost
            DATABASE_PORT: 5432
            DATABASE_USERNAME: postgres
            DATABASE_NAME: social_media_app
            DATABASE_PASSWORD: rayen
            SECRET_KEY: 4F29FH29AFBN921GHF92BG92AB934GB92
            ALGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 60
        runs-on: ubuntu-latest
        steps:
            -   name: Pulling Git Repo
                uses: actions/checkout@v4
            -   name: Install Python Version 3.14
                uses: actions/setup-python@v7
                with:
                    python-version: "3.14"
            -   name: Upgrade Pip
                run: python3 -m pip install --upgrade pip
            -   name: Install Dependencies
                run: pip install -r requirements.txt
            -   name: Run Tests With Pytest
                run: |
                    pip install pytest
                    pytest -v

